name: TS-Project
run-name: AWS create resources
on: [push]
jobs:
  Deploy_App:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is working"
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: List file in repo
        run: ls ${{ github.workspace }}
      # Install the deps
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - name: check if aws cli is installed
        run: |
          aws --version
      - name: install terraform
        uses: hashicorp/setup-terraform@v2
      - run: terraform version
      # Configure aws-cli
      - run: mkdir -p ~/.aws/
      - run: echo "$super_secret" > ~/.aws/credentials
        env:
          super_secret: ${{ secrets.AWS_CONFIG }}
      - run: cat ~/.aws/credentials
      - run: aws configure list-profiles
      - run: aws s3 ls --region eu-central-1 --profile techstarter
      # Terraform stuff :)
      - run: terraform -chdir=terraform/ init -backend-config="bucket=${STATE_BUCKET}"
        env:
          STATE_BUCKET: ${{ secrets.TF_BUCKET }}
      - run: terraform -chdir=terraform/ plan
      - run: terraform -chdir=terraform/ apply -auto-approve
      - run: |
          terraform -chdir=terraform/ output -raw inventory > ansible/inventory
          tail -n +2 ansible/inventory > ansible/inventory.ini
      - run: |
          terraform -chdir=terraform/ output -raw private_key > ssh
          tail -n +2 ssh > ssh_key
      # Setup ssh for ansible
      - run: |
          mkdir -p /home/runner/.ssh 
          cp ssh_key /home/runner/.ssh/id_rsa
          chmod 700 /home/runner/.ssh/id_rsa
      - run: |
          service ssh status
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook --private-key /home/runner/.ssh/id_rsa -u ubuntu -i ansible/inventory.ini --extra-vars "ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa"
